### ISSUE TITLE
Load settings from user settings too

### ISSUE THREAD

**Issue by borela** [ihodev/a-file-icon#89]
#### Expected Behavior
Have the settings related to this package in the `Preferences > Settings`. An example of how it would work, look at the [Material Theme Settings](https://github.com/equinusocio/material-theme#theme-options).

#### Current Behavior
To change the settings, you need to add it to the package settings.

#### Context
It is nice to have all the required settings into a single file, easier when you go to a new computer and the settings can shared using a single gist.

#### Your Environment
Platform: windows
A File Icon: 3.0.1
Sublime Text: 3126
Package Control: True
Current Theme: Material-Theme.sublime-theme
Installed Themes:
* Theme - Default
* Material Theme

**Comment by ihodev** [comment]
Hello, @borela ! I doubt that's a good solution, because it's easier to deal with plugin's only settings and it's a way that most ST plugins do. The only reason why `Material Theme` or any other theme with settings store them in `Preferences.sublime-settings` – there's no other solution for themes.

The easiest way to migrate your settings to a new computer is just copy the `User` folder.

I don't know how many users want the behavior you explained above. That's why I leave this for voting.

**Comment by ihodev** [comment]
Sorry, I'm closing this issue because not many users want this behavior.
